/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: dachidachi301 (https://sketchfab.com/dachidachi301)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/9b78e9189c284e4bae9b36c669408d6e
title: Computer 1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tisch.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-63, -58, 0]}>
          <mesh geometry={nodes.mesh_0.geometry} material={materials.palette} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tisch.gltf')
